
<form style="width:500px; margin:0 auto;" action="<?= $block->escapeUrl($block->getUrl('digital-boutique/index/save')) ?>" name='form' id='form' method='POST' accept-charset='UTF-8' enctype='multipart/form-data' data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field required">
            <label class="label"><span><?= $block->escapeHtml(__('Product SKU')) ?></span></label>
            <div class="control">
                <input class="input-text" type="text" name="product_sku" title="<?= $block->escapeHtmlAttr(__('Product SKU')) ?>" fieldType=1 maxlength="255" data-validate="{required:true}" />
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary" value="<?= $block->escapeHtml(__('Submit')) ?>" />
        </div>
    </div>
</form>